table facilities
	lineageTag: 95a90133-8797-4ec5-9be6-b2ce6c4ff713

	column facility_id
		dataType: string
		lineageTag: f3ee2a67-76b4-4998-b91c-bbeebbdd1bac
		summarizeBy: none
		sourceColumn: facility_id

		annotation SummarizationSetBy = Automatic

	column facility_name
		dataType: string
		lineageTag: 3bbd2ac0-d9f4-4784-a1e3-db61ff89a8dc
		summarizeBy: none
		sourceColumn: facility_name

		annotation SummarizationSetBy = Automatic

	column facility_type
		dataType: string
		lineageTag: e9f416af-f2d0-4291-b8c6-1ba1f9347a65
		summarizeBy: none
		sourceColumn: facility_type

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 73b039fc-4ca2-4ac9-adbb-30275047c40d
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 5accbbfd-6edf-47b4-a7ec-f0b586ada433
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 54a8731b-9ad2-47fa-9091-e45c3a180a59
		summarizeBy: none
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: bc7ee836-846a-4a15-986c-bfa4c78935f8
		summarizeBy: none
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dock_doors
		dataType: int64
		formatString: 0
		lineageTag: 105be2ac-1b38-482e-8883-bd9547ca7e99
		summarizeBy: none
		sourceColumn: dock_doors

		annotation SummarizationSetBy = Automatic

	column operating_hours
		dataType: string
		lineageTag: 29aba4c6-0f2e-409b-8309-b5d73051da63
		summarizeBy: none
		sourceColumn: operating_hours

		annotation SummarizationSetBy = Automatic

	partition facilities = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\pc\Desktop\DEPI\final project\data cleaned\facilities.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"facility_id", type text}, {"facility_name", type text}, {"facility_type", type text}, {"city", type text}, {"state", type text}, {"latitude", type number}, {"longitude", type number}, {"dock_doors", Int64.Type}, {"operating_hours", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

