table maintenance_records
	lineageTag: ad1a9223-471b-4a4e-9909-b34fe897b75c

	column maintenance_id
		dataType: string
		lineageTag: 54457ac1-757c-44ae-bb36-61a98ea39c36
		summarizeBy: none
		sourceColumn: maintenance_id

		annotation SummarizationSetBy = Automatic

	column truck_id
		dataType: string
		lineageTag: 921baf56-4da4-490e-8d56-c2385513358f
		summarizeBy: none
		sourceColumn: truck_id

		annotation SummarizationSetBy = Automatic

	column maintenance_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: bc6d5748-6a0a-4d48-bc5e-db39412da086
		summarizeBy: none
		sourceColumn: maintenance_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column maintenance_type
		dataType: string
		lineageTag: 78d0d112-ea4b-4337-b0e9-16215c395ab3
		summarizeBy: none
		sourceColumn: maintenance_type

		annotation SummarizationSetBy = Automatic

	column odometer_reading
		dataType: int64
		formatString: 0
		lineageTag: ff04eec3-77ea-4374-a36a-c1db47438bb8
		summarizeBy: sum
		sourceColumn: odometer_reading

		annotation SummarizationSetBy = Automatic

	column labor_hours
		dataType: double
		lineageTag: ae13fd69-41e9-4318-91b2-955b4d907c54
		summarizeBy: sum
		sourceColumn: labor_hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column labor_cost
		dataType: double
		lineageTag: 6996abe7-ddfb-433a-8343-9e80b213b3ba
		summarizeBy: sum
		sourceColumn: labor_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column parts_cost
		dataType: double
		lineageTag: 6a3bb2fc-32bb-43dc-bfbe-2869f24236fc
		summarizeBy: sum
		sourceColumn: parts_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_cost
		dataType: double
		lineageTag: 48940a10-10a2-4980-a9e4-50e013d747b2
		summarizeBy: sum
		sourceColumn: total_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column facility_location
		dataType: string
		lineageTag: 07401005-e7ad-4edf-ae6d-25024d93e1c5
		summarizeBy: none
		sourceColumn: facility_location

		annotation SummarizationSetBy = Automatic

	column downtime_hours
		dataType: double
		lineageTag: 3e9a6df7-6ea4-4daa-9710-4eba60fc8ba4
		summarizeBy: sum
		sourceColumn: downtime_hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column service_description
		dataType: string
		lineageTag: 97f6b5c0-9528-4b86-b964-ae667e9657c3
		summarizeBy: none
		sourceColumn: service_description

		annotation SummarizationSetBy = Automatic

	partition maintenance_records = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\pc\Desktop\DEPI\final project\data cleaned\maintenance_records.csv"),[Delimiter=",", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"maintenance_id", type text}, {"truck_id", type text}, {"maintenance_date", type date}, {"maintenance_type", type text}, {"odometer_reading", Int64.Type}, {"labor_hours", type number}, {"labor_cost", type number}, {"parts_cost", type number}, {"total_cost", type number}, {"facility_location", type text}, {"downtime_hours", type number}, {"service_description", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

