table routes
	lineageTag: a0b67992-9f70-4e7d-b00b-f3325e69f83f

	column route_id
		dataType: string
		lineageTag: e9f1e2c5-20dd-4799-aa74-4b04c762d4b5
		summarizeBy: none
		sourceColumn: route_id

		annotation SummarizationSetBy = Automatic

	column origin_city
		dataType: string
		lineageTag: 22846a1f-c3d3-463c-bcd5-11efefb3f1cb
		summarizeBy: none
		sourceColumn: origin_city

		annotation SummarizationSetBy = Automatic

	column origin_state
		dataType: string
		lineageTag: 3ba2c593-999d-41e4-be5c-6d777d8abe6b
		summarizeBy: none
		sourceColumn: origin_state

		annotation SummarizationSetBy = Automatic

	column destination_city
		dataType: string
		lineageTag: 53c73857-7716-4fa5-8693-3d13241dbcc8
		summarizeBy: none
		sourceColumn: destination_city

		annotation SummarizationSetBy = Automatic

	column destination_state
		dataType: string
		lineageTag: 0843e66c-46cd-46c1-bf3e-6989327f1648
		summarizeBy: none
		sourceColumn: destination_state

		annotation SummarizationSetBy = Automatic

	column typical_distance_miles
		dataType: int64
		formatString: 0
		lineageTag: 15f599d4-f14c-49f5-8621-c482ef5060a1
		summarizeBy: none
		sourceColumn: typical_distance_miles

		annotation SummarizationSetBy = Automatic

	column base_rate_per_mile
		dataType: double
		lineageTag: e41a4c11-1a05-49fa-b77b-439280f84a36
		summarizeBy: none
		sourceColumn: base_rate_per_mile

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fuel_surcharge_rate
		dataType: double
		lineageTag: 2cc3ca3d-c0e1-471b-9bfc-6fe80d7eb77c
		summarizeBy: none
		sourceColumn: fuel_surcharge_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column typical_transit_days
		dataType: int64
		formatString: 0
		lineageTag: ff87ffc5-8501-4ccc-ba52-ba5bcd58e63d
		summarizeBy: none
		sourceColumn: typical_transit_days

		annotation SummarizationSetBy = Automatic

	partition routes = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\pc\Desktop\DEPI\final project\data cleaned\routes.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"route_id", type text}, {"origin_city", type text}, {"origin_state", type text}, {"destination_city", type text}, {"destination_state", type text}, {"typical_distance_miles", Int64.Type}, {"base_rate_per_mile", type number}, {"fuel_surcharge_rate", type number}, {"typical_transit_days", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

