table safety_incidents
	lineageTag: 6456a20d-83a2-460a-8a83-85290e05c4b5

	column incident_id
		dataType: string
		lineageTag: 8ece4e65-c1b3-41c9-8057-50c8071ddf73
		summarizeBy: none
		sourceColumn: incident_id

		annotation SummarizationSetBy = Automatic

	column trip_id
		dataType: string
		lineageTag: fc8120a6-b943-4952-af3e-2b65aa168f2c
		summarizeBy: none
		sourceColumn: trip_id

		annotation SummarizationSetBy = Automatic

	column truck_id
		dataType: string
		lineageTag: bdfb783d-77b8-4e56-80fa-5dad26478805
		summarizeBy: none
		sourceColumn: truck_id

		annotation SummarizationSetBy = Automatic

	column driver_id
		dataType: string
		lineageTag: 40852c0e-e2f1-458f-9bbd-9e6c1f7767d2
		summarizeBy: none
		sourceColumn: driver_id

		annotation SummarizationSetBy = Automatic

	column incident_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 0580d1dc-3a71-49f5-88ed-eb9a5701e152
		summarizeBy: none
		sourceColumn: incident_date

		annotation SummarizationSetBy = Automatic

	column incident_type
		dataType: string
		lineageTag: dd5aa25c-e65f-437e-888c-f33d86f6d2eb
		summarizeBy: none
		sourceColumn: incident_type

		annotation SummarizationSetBy = Automatic

	column location_city
		dataType: string
		lineageTag: bb459f3c-1279-4769-b5d6-d7f9842e86b5
		summarizeBy: none
		sourceColumn: location_city

		annotation SummarizationSetBy = Automatic

	column location_state
		dataType: string
		lineageTag: c8934d85-866f-4811-9627-234384a04308
		summarizeBy: none
		sourceColumn: location_state

		annotation SummarizationSetBy = Automatic

	column at_fault_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9303d3ba-7f45-4f42-b2ea-e85a61c4a051
		summarizeBy: none
		sourceColumn: at_fault_flag

		annotation SummarizationSetBy = Automatic

	column injury_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ff51edfc-a8ad-40a6-a37f-0296311079e8
		summarizeBy: none
		sourceColumn: injury_flag

		annotation SummarizationSetBy = Automatic

	column vehicle_damage_cost
		dataType: double
		lineageTag: fa227eb8-37ff-48da-8325-5e8da6957378
		summarizeBy: sum
		sourceColumn: vehicle_damage_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cargo_damage_cost
		dataType: double
		lineageTag: 4f70f096-2a19-420e-90da-9903c0eb4cfb
		summarizeBy: sum
		sourceColumn: cargo_damage_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column claim_amount
		dataType: double
		lineageTag: 8837703e-248a-484b-98b3-f11c7d531b89
		summarizeBy: sum
		sourceColumn: claim_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column preventable_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 00ccff93-3779-42d5-a10d-a2c54cdefaf8
		summarizeBy: none
		sourceColumn: preventable_flag

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 588c2197-8f1a-417d-88d7-5b45ce742a9e
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	partition safety_incidents = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\pc\Desktop\DEPI\final project\data cleaned\safety_incidents.csv"),[Delimiter=",", Columns=15, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"incident_id", type text}, {"trip_id", type text}, {"truck_id", type text}, {"driver_id", type text}, {"incident_date", type datetime}, {"incident_type", type text}, {"location_city", type text}, {"location_state", type text}, {"at_fault_flag", type logical}, {"injury_flag", type logical}, {"vehicle_damage_cost", type number}, {"cargo_damage_cost", type number}, {"claim_amount", type number}, {"preventable_flag", type logical}, {"description", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

