table fuel_purchases
	lineageTag: 2a4c3d90-1f8c-4951-9ef7-6125e92e7f32

	column fuel_purchase_id
		dataType: string
		lineageTag: 8541bdd7-136e-4160-a31c-96a3de0f4f9b
		summarizeBy: none
		sourceColumn: fuel_purchase_id

		annotation SummarizationSetBy = Automatic

	column trip_id
		dataType: string
		lineageTag: 2e21b3dd-8784-406d-ae6d-8e03560c3176
		summarizeBy: none
		sourceColumn: trip_id

		annotation SummarizationSetBy = Automatic

	column truck_id
		dataType: string
		lineageTag: bcfb9f2c-14f2-4e9d-a053-1a6d3b33465a
		summarizeBy: none
		sourceColumn: truck_id

		annotation SummarizationSetBy = Automatic

	column driver_id
		dataType: string
		lineageTag: ecfd19e8-b761-4d37-a653-888aa5b1ce79
		summarizeBy: none
		sourceColumn: driver_id

		annotation SummarizationSetBy = Automatic

	column purchase_date
		dataType: dateTime
		formatString: General Date
		lineageTag: d899f18c-49da-4dfc-b032-fc69188e84e8
		summarizeBy: none
		sourceColumn: purchase_date

		annotation SummarizationSetBy = Automatic

	column location_city
		dataType: string
		lineageTag: 2cbb6d85-b510-48a2-b110-08673e9dc480
		summarizeBy: none
		sourceColumn: location_city

		annotation SummarizationSetBy = Automatic

	column location_state
		dataType: string
		lineageTag: 08357168-af32-466a-945e-0916cf26841e
		summarizeBy: none
		sourceColumn: location_state

		annotation SummarizationSetBy = Automatic

	column gallons
		dataType: double
		lineageTag: 9d090f2d-c456-4a49-8578-b3c559b08221
		summarizeBy: sum
		sourceColumn: gallons

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column price_per_gallon
		dataType: double
		lineageTag: 05abb05b-60b0-464c-aeb2-603cf6f8f6df
		summarizeBy: sum
		sourceColumn: price_per_gallon

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_cost
		dataType: double
		lineageTag: 0b7dd391-cde8-4777-bbe9-148fef25b77c
		summarizeBy: sum
		sourceColumn: total_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fuel_card_number
		dataType: string
		lineageTag: 8910c6f8-5873-433b-95ad-60b24593e4a7
		summarizeBy: none
		sourceColumn: fuel_card_number

		annotation SummarizationSetBy = Automatic

	partition fuel_purchases = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\pc\Desktop\DEPI\final project\data cleaned\fuel_purchases.csv"),[Delimiter=",", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"fuel_purchase_id", type text}, {"trip_id", type text}, {"truck_id", type text}, {"driver_id", type text}, {"purchase_date", type datetime}, {"location_city", type text}, {"location_state", type text}, {"gallons", type number}, {"price_per_gallon", type number}, {"total_cost", type number}, {"fuel_card_number", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

