table loads
	lineageTag: 65461873-6f92-4865-9a66-fb8475a4ca6e

	column load_id
		dataType: string
		lineageTag: 14ccb869-da14-49a0-bebb-2d7118db0c58
		summarizeBy: none
		sourceColumn: load_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: f81db6b9-65a4-4b67-a405-4c429bb17680
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column route_id
		dataType: string
		lineageTag: 95122ae9-b2a3-436e-8a97-3889b6d84ccb
		summarizeBy: none
		sourceColumn: route_id

		annotation SummarizationSetBy = Automatic

	column load_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e7398759-1018-4e70-89fe-937b8daadf99
		summarizeBy: none
		sourceColumn: load_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column load_type
		dataType: string
		lineageTag: 92d144df-6f17-4447-95da-518fd37ea58e
		summarizeBy: none
		sourceColumn: load_type

		annotation SummarizationSetBy = Automatic

	column weight_lbs
		dataType: int64
		formatString: 0
		lineageTag: 681bc5b1-7ed9-4e19-9f3b-e9b82ab261dc
		summarizeBy: sum
		sourceColumn: weight_lbs

		annotation SummarizationSetBy = Automatic

	column pieces
		dataType: int64
		formatString: 0
		lineageTag: e11d00d6-3a63-48b0-bd02-e98f0b9bdaa0
		summarizeBy: sum
		sourceColumn: pieces

		annotation SummarizationSetBy = Automatic

	column revenue
		dataType: double
		lineageTag: e18c0884-f7e0-4dc3-88c9-a5ac6ce03d5b
		summarizeBy: sum
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fuel_surcharge
		dataType: double
		lineageTag: bd29ab47-26f3-4c77-a4de-96c79fe8dfc7
		summarizeBy: sum
		sourceColumn: fuel_surcharge

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column accessorial_charges
		dataType: int64
		formatString: 0
		lineageTag: 21bab12b-2a6a-4f42-8f9d-3737885caf2e
		summarizeBy: sum
		sourceColumn: accessorial_charges

		annotation SummarizationSetBy = Automatic

	column load_status
		dataType: string
		lineageTag: ba203597-ce06-45e1-ace7-8a723ed05f33
		summarizeBy: none
		sourceColumn: load_status

		annotation SummarizationSetBy = Automatic

	column booking_type
		dataType: string
		lineageTag: 533e2437-f8a6-4404-a565-00408a5db79f
		summarizeBy: none
		sourceColumn: booking_type

		annotation SummarizationSetBy = Automatic

	partition loads = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\pc\Desktop\DEPI\final project\data cleaned\loads.csv"),[Delimiter=",", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"load_id", type text}, {"customer_id", type text}, {"route_id", type text}, {"load_date", type date}, {"load_type", type text}, {"weight_lbs", Int64.Type}, {"pieces", Int64.Type}, {"revenue", type number}, {"fuel_surcharge", type number}, {"accessorial_charges", Int64.Type}, {"load_status", type text}, {"booking_type", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

