table trailers
	lineageTag: 2a2c5699-1445-43dc-965b-7e7e623c7060

	column trailer_id
		dataType: string
		lineageTag: b28f2e9e-de10-485c-bf5a-0b7d41e540df
		summarizeBy: none
		sourceColumn: trailer_id

		annotation SummarizationSetBy = Automatic

	column trailer_number
		dataType: int64
		formatString: 0
		lineageTag: 3fcef8e7-2caf-45fe-acc8-5f0c1fc3ac28
		summarizeBy: none
		sourceColumn: trailer_number

		annotation SummarizationSetBy = Automatic

	column trailer_type
		dataType: string
		lineageTag: ea513088-5a2c-40f3-87f3-2870f388c949
		summarizeBy: none
		sourceColumn: trailer_type

		annotation SummarizationSetBy = Automatic

	column length_feet
		dataType: int64
		formatString: 0
		lineageTag: fb511159-d699-4c89-85c5-0bf5c7904c8d
		summarizeBy: none
		sourceColumn: length_feet

		annotation SummarizationSetBy = Automatic

	column model_year
		dataType: int64
		formatString: 0
		lineageTag: 062ca9d4-4888-4a09-abc0-abfcefb8527a
		summarizeBy: none
		sourceColumn: model_year

		annotation SummarizationSetBy = Automatic

	column vin
		dataType: string
		lineageTag: 77e85bfc-10ef-4b92-b827-c7d6b1bb7fde
		summarizeBy: none
		sourceColumn: vin

		annotation SummarizationSetBy = Automatic

	column acquisition_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 28d9d1eb-7c80-43bf-b540-462ee3168059
		summarizeBy: none
		sourceColumn: acquisition_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column status
		dataType: string
		lineageTag: 9e66cd12-9e5a-4dde-8907-950273309831
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column current_location
		dataType: string
		lineageTag: ee1107a6-3d42-45a6-8ee7-3a9682cdce0c
		summarizeBy: none
		sourceColumn: current_location

		annotation SummarizationSetBy = Automatic

	partition trailers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\pc\Desktop\DEPI\final project\data cleaned\trailers.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"trailer_id", type text}, {"trailer_number", Int64.Type}, {"trailer_type", type text}, {"length_feet", Int64.Type}, {"model_year", Int64.Type}, {"vin", type text}, {"acquisition_date", type date}, {"status", type text}, {"current_location", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

